[format.rules]
array-bracket-space-width = 1
array-comma-space-width = 1
indent-style = "tab"
inline-table-brace-space-width = 1
inline-table-comma-space-width = 1
key-value-equals-sign-alignment = true
key-value-equals-sign-space-width = 1
line-width = 160
string-quote-style = "preserve"
